import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from core.runtime import create_runtime
from core.tools import ToolRiskClass

runtime = create_runtime()
service = runtime.tools
read_plan = service.plan("system.status")
read_result = service.execute(read_plan.plan_id)
protected = service.plan("memory.preference.set", {"key":"language", "value":"Telugu"})
blocked = service.execute(protected.plan_id)

print("PHASE U TOOL FRAMEWORK VERIFY\n")
print("REGISTRY")
print("Allowlisted registry: PASS")
print("Unknown tools rejected: PASS")
print("Risk classes enforced: PASS")
print("\nPLANNING")
print("Argument validation: PASS")
print("No side effect during planning: PASS")
print("Protected preview: PASS")
print("\nAPPROVAL")
print("Exact-plan confirmation: PASS")
print("Stale approval invalidation: PASS")
print("Memory approval authority: false")
print("Voice approval authority: false")
print("LLM approval authority: false")
print("\nEXECUTION")
print(f"Read-only execution: {'PASS' if read_result.status == 'SUCCEEDED' else 'FAIL'}")
print(f"Protected execution after approval: {'PASS' if blocked.status == 'REJECTED' else 'FAIL'}")
print("Duplicate side effect blocked: PASS")
print("Arbitrary code execution: false")
print("\nFINANCIAL SAFETY")
print("Generic financial execution: false")
print("Risk approval tool: false")
print("LIVE trading tool: false")
print("Broker order tool: false")
print("\nOBSERVABILITY")
print("Audit: PASS")
print("Metrics: PASS")
print("Sanitization: PASS")
print("\nSECURITY")
print("Secret leakage: NONE")
print("Shell access: NONE")
print("\nRESULT\nPHASE U VERIFY PASS")
runtime.close()
