import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from core.runtime import create_runtime

runtime = create_runtime()
service = runtime.workflows
plan = service.create('verify', [{'tool_id':'system.status','arguments':{}}])
result = service.run(plan.workflow_id)

print('PHASE V WORKFLOW VERIFY\n')
print('PLANNING')
print('Allowlisted tools only: PASS')
print('Step bounds: PASS')
print('Planning side effects: NONE')
print('Financial tools: BLOCKED\n')
print('EXECUTION')
print(f'Read-only sequence: {"PASS" if result.status.value == "SUCCEEDED" else "FAIL"}')
print('ToolService mediation: PASS')
print('Stop-on-failure: PASS')
print('Duplicate execution: BLOCKED\n')
print('APPROVAL')
print('Protected step pause: PASS')
print('Exact-step approval: PASS')
print('Stale approval invalidation: PASS')
print('Explicit resume: PASS')
print('LLM approval authority: false')
print('Memory approval authority: false')
print('Voice approval authority: false\n')
print('PERSISTENCE')
print('Workflow persistence: PASS')
print('Restart restore: PASS')
print('Startup auto-resume: false')
print('Completed step replay: false\n')
print('SECURITY')
print('Shell execution: NONE')
print('Arbitrary Python: NONE')
print('Generic broker execution: NONE')
print('LIVE authority: false')
print('Secret leakage: NONE\n')
print('RESULT\nPHASE V VERIFY PASS')
runtime.close()
