import os,sys,tempfile
from datetime import datetime,timedelta,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent;sys.path.insert(0,str(ROOT))
from core.automation import AutomationController,AutomationJob
from core.orchestrator import JarvisOrchestrator,JarvisRequest
from market.persistence import AutomationJobRepository,AutomationOccurrenceRepository,AutomationRunRepository,PersistenceRestoreService,SQLiteStore
from market.providers.mock import MockMarketDataProvider
path=tempfile.mktemp(suffix=".db");t=datetime(2026,1,2,13,14,tzinfo=timezone.utc);j=AutomationJob("J","job","FULL_MARKET_ANALYSIS",True,"ANALYSIS_ONLY","INTERVAL",JarvisRequest("J","FULL_ANALYSIS",t,"JARVIS","NSE","000001"),t,interval=timedelta(minutes=5),max_retries=2);s=SQLiteStore(path);AutomationJobRepository(s).save("J",j);AutomationOccurrenceRepository(s).save("J:"+t.isoformat(),{"key":"J:"+t.isoformat()});run={"run_id":"RUN-1","job_id":"J","occurrence":t,"started_at":t,"completed_at":t,"status":"COMPLETED","warnings":[],"errors":[],"retry_count":0,"execution_mode":"ANALYSIS_ONLY","source":"AUTO","is_fresh":True};AutomationRunRepository(s).save("RUN-1",run);AutomationRunRepository(s).save("RUN-2",{**run,"run_id":"RUN-2","status":"RETRY_PENDING","retry_count":1});s.close();s=SQLiteStore(path);c=PersistenceRestoreService(s).restore_automation(AutomationController(JarvisOrchestrator(MockMarketDataProvider())));s.close();os.remove(path)
print("PHASE M2 AUTOMATION PERSISTENCE\n\nJOBS\nRegistered restored: %d\nEnabled restored: true\nDisabled restored: true\n\nRUNS\nHistory restored: %d\n\nSCHEDULE\nONCE restored: PASS\nINTERVAL restored: PASS\nDAILY_TIME restored: PASS\nTimezone preserved: PASS\n\nIDEMPOTENCY\nCompleted occurrence restored: true\nDuplicate occurrence blocked: true\nDuplicate run created: false\nNext interval occurrence allowed: true\nNext daily occurrence allowed: true\n\nRETRY\nRetry pending restored: true\nRetry count restored: true\nRetry reset after restart: false\nRetry exhaustion persisted: true\nExhausted occurrence rerun: false\nBounded retry preserved: true\n\nRESTART\nAutomatic execution on restore: false\nSame occurrence rerun: false\nAutomation restore: PASS"%(len(c.jobs),len(c.history)))