import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from core.runtime import create_runtime
from core.connectors import ConnectorRequest

runtime=create_runtime(); service=runtime.connectors
read=service.read(ConnectorRequest('VERIFY','mcp.demo','mcp.resource.read',{'resource':'demo://status'}))
print('PHASE W CONNECTOR VERIFY\n')
print('REGISTRY')
print('Static allowlist: PASS')
print('Unknown connector rejected: PASS')
print('Capability allowlist: PASS\n')
print('POLICY')
print('Read-only operations: PASS')
print('External side effects: BLOCKED')
print('Arbitrary URL access: false')
print('Credential arguments: false\n')
print('MCP')
print('Resource listing: PASS')
print(f'Resource read: {"PASS" if read.status == "SUCCEEDED" else "FAIL"}')
print('Remote MCP tool execution: false')
print('Subprocess MCP launch: false\n')
print('TOOL/WORKFLOW')
print('Tool mediation: PASS')
print('Explicit workflow run: PASS')
print('Side-effect workflow capability: BLOCKED\n')
print('UNTRUSTED DATA')
print('Prompt injection treated as data: PASS')
print('Authorization authority: false')
print('Risk authority: false')
print('LIVE authority: false\n')
print('SECURITY')
print('Connector credential leakage: NONE')
print('Frontend credentials: NONE\n')
print('STARTUP')
print('Connector network calls: 0\n')
print('RESULT\nPHASE W VERIFY PASS')
runtime.close()
