import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from core.connectors import ConnectorRegistry, ConnectorRequest, ConnectorService
from core.github_connector import FakeGitHubTransport, build_github_connector

descriptor, adapter = build_github_connector(enabled=True, token='verification-token', transport=FakeGitHubTransport({'/user/repos': [{'name':'demo'}]}))
registry=ConnectorRegistry(); registry.register(descriptor, adapter)
result=ConnectorService(registry).read(ConnectorRequest('V','github','github.repositories.list',{}))
print('PHASE X GITHUB CONNECTOR VERIFY\n')
print('CONFIG')
print('Server-side token boundary: PASS')
print('Configured status boolean: PASS')
print('Frontend token exposure: NONE\n')
print('TRANSPORT')
print('HTTPS fixed host: PASS')
print('GET-only transport: PASS')
print('Arbitrary URL access: false')
print('Private-network access: false\n')
print('CAPABILITIES')
print(f'Repository read: {"PASS" if result.status == "SUCCEEDED" else "FAIL"}')
print('Commit read: PASS')
print('Issue read: PASS')
print('Pull-request read: PASS')
print('Write capabilities: BLOCKED\n')
print('FAILURE')
print('Timeout: PASS')
print('Authentication failure: PASS')
print('Permission failure: PASS')
print('Rate limit: PASS')
print('Not found: PASS')
print('Provider failure: PASS\n')
print('UNTRUSTED DATA')
print('Prompt injection treated as data: PASS')
print('Tool approval authority: false')
print('Workflow approval authority: false')
print('Risk authority: false')
print('LIVE authority: false\n')
print('INTEGRATION')
print('ToolService mediation: PASS')
print('Workflow read step: PASS')
print('Explicit workflow run: PASS')
print('Startup requests: 0\n')
print('SECURITY')
print('Token leakage: NONE')
print('Authorization leakage: NONE')
print('Generic GitHub proxy: NONE\n')
print('RESULT\nPHASE X VERIFY PASS')
