import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {App} from './main.tsx';
import {ResultPanel} from './components/ResultPanel.tsx';
import {api} from './api/client';
vi.mock(import('./api/client'),()=>({api:vi.fn(async()=>({status:'OK',message:'F&O DATA NOT AVAILABLE'}))}));
afterEach(cleanup);
beforeEach(()=>vi.mocked(api).mockReset().mockResolvedValue({status:'OK',message:'F&O DATA NOT AVAILABLE'}));
describe('JARVIS UI',()=>{
 it('renders dashboard safety and diagnostics state',async()=>{render(<App/>);await waitFor(()=>expect(screen.getByText('LIVE EXECUTION: UNSUPPORTED')).toBeTruthy());await waitFor(()=>expect(screen.getByText(/F&O DATA NOT AVAILABLE|Request unavailable\./i)).toBeTruthy());});
 it('renders health, readiness, metrics and diagnostics from backend state',async()=>{vi.mocked(api).mockImplementation(async(path:string)=>{
   if(path==='/api/v1/diagnostics'){return {status:'OK',health:{status:'HEALTHY'},readiness:{status:'READY'},metrics:{requests_total:17,requests_failed:1,automation_runs_total:2,automation_failures:1,paper_orders_total:3,backtests_total:1},diagnostics:{provider_configured:true,persistence_state:'OK',guardrails:{max_jobs:2},live_execution_supported:false}};}
   return {status:'OK',message:'F&O DATA NOT AVAILABLE'}; }); render(<App/>); await waitFor(()=>expect(screen.getByText('LIVE EXECUTION: UNSUPPORTED')).toBeTruthy()); expect(screen.getByText('READY')).toBeTruthy(); expect(screen.getByText('17')).toBeTruthy(); expect(screen.getByText('provider_configured')).toBeTruthy(); expect(screen.getByText('live_execution_supported')).toBeTruthy(); });
 it('shows loading and safe error states',async()=>{vi.mocked(api).mockImplementation(async(path:string)=>{ if(path==='/api/v1/diagnostics'){ return new Promise(resolve=>setTimeout(()=>resolve({status:'OK',message:'F&O DATA NOT AVAILABLE'}),50)); } return {status:'OK',message:'F&O DATA NOT AVAILABLE'}; }); const {unmount}=render(<App/>); expect(screen.getByText('LOADING...')).toBeTruthy(); await waitFor(()=>expect(screen.getByText(/F&O DATA NOT AVAILABLE/)).toBeTruthy()); unmount(); vi.mocked(api).mockImplementation(async(path:string)=>{ if(path==='/api/v1/diagnostics'){ return new Promise((_, reject)=>setTimeout(()=>reject(new Error('boom')), 10)); } return {status:'OK',message:'F&O DATA NOT AVAILABLE'}; }); render(<App/>); await waitFor(()=>expect(screen.getByText('Request unavailable.')).toBeTruthy()); });
 it('sends one chat request and preserves Telugu text',async()=>{render(<App/>);fireEvent.click(screen.getByText('Chat'));const input=screen.getByLabelText('Message');fireEvent.change(input,{target:{value:'నా portfolio చూపించు'}});fireEvent.click(screen.getByText('Send'));await waitFor(()=>expect(screen.getByDisplayValue('నా portfolio చూపించు')).toBeTruthy())});
 it('renders follow-up, warnings, missing fields and structured_result',async()=>{vi.mocked(api).mockImplementation(async(path:string)=>{ if(path==='/api/v1/chat'){ return {message:'Need more data',intent:'analysis',follow_up_required:true,missing_fields:['symbol'],warnings:['insufficient context'],structured_result:{instrument:'RELIANCE',freshness:'fresh'}}; } return {status:'OK',message:'F&O DATA NOT AVAILABLE'}; }); render(<App/>); fireEvent.click(screen.getByText('Chat')); fireEvent.change(screen.getByLabelText('Message'),{target:{value:'Explain RIL'}}); fireEvent.click(screen.getByText('Send')); await waitFor(()=>expect(screen.getByText(/FOLLOW_UP_REQUIRED/)).toBeTruthy()); expect(screen.getByText(/Missing:/)).toBeTruthy(); expect(screen.getByText(/Warnings:/)).toBeTruthy(); expect(screen.getByText(/Intent:/)).toBeTruthy(); });
 it('sends one chat request only once',async()=>{const mock=vi.mocked(api); mock.mockImplementation(async(path:string)=> path==='/api/v1/chat' ? {message:'ok'} : {status:'OK',message:'F&O DATA NOT AVAILABLE'}); render(<App/>); fireEvent.click(screen.getByText('Chat')); fireEvent.change(screen.getByLabelText('Message'),{target:{value:'hello'}}); fireEvent.click(screen.getByText('Send')); await waitFor(()=>expect(mock.mock.calls.filter(([path])=>path==='/api/v1/chat')).toHaveLength(1)); });
 it('shows analysis, paper, backtest and automation safety views',()=>{render(<App/>);fireEvent.click(screen.getByText('Analysis'));expect(screen.getByText('Full Analysis')).toBeTruthy();fireEvent.click(screen.getByText('Paper Trading'));expect(screen.getByText(/PAPER TRADING only/)).toBeTruthy();fireEvent.click(screen.getByText('Backtests'));expect(screen.getByText(/HISTORICAL REPLAY/)).toBeTruthy();fireEvent.click(screen.getByText('Automation'));expect(screen.getByText('Run Tick')).toBeTruthy()});
 it('renders semantic analysis, confluence, strategy, and F&O unavailable fields',()=>{render(<ResultPanel data={{result:{underlying_analysis:{instrument:'RELIANCE',trend:'BULLISH',is_fresh:true},confluence_analysis:{directional_bias:'BULLISH',bullish_score:3,bearish_score:1,net_evidence_score:2,evidence_quality:'MEDIUM',data_completeness:'COMPLETE'},strategy_evidence:[{strategy_name:'TREND',direction:'BULLISH',evidence_strength:'HIGH'}],warnings:['FNO_DATA = NOT_AVAILABLE']}}}/>);expect(screen.getByText('RELIANCE')).toBeTruthy();expect(screen.getByText('Strategy Evidence')).toBeTruthy();expect(screen.getByText('F&O DATA NOT AVAILABLE')).toBeTruthy()});
 it('blocks Paper execution until approval and authorization',()=>{render(<App/>);fireEvent.click(screen.getByText('Paper Trading'));const execute=screen.getByText('Execute PAPER trade') as HTMLButtonElement;expect(execute.disabled).toBe(true);const checkbox=screen.getByLabelText('I authorize this PAPER trade') as HTMLInputElement;expect(checkbox.checked).toBe(false);fireEvent.click(checkbox);expect(execute.disabled).toBe(true)});
 it('uses backend risk approval, requires authorization, and invalidates stale approval',async()=>{const mock=vi.mocked(api);mock.mockImplementation(async path=>path==='/api/v1/risk/validate'?{result:{risk_decision:{approved:true}}}:{status:'OK',message:'F&O DATA NOT AVAILABLE'});render(<App/>);fireEvent.click(screen.getByText('Paper Trading'));for(const [label,value] of Object.entries({proposed_entry:'100',proposed_stop:'98',proposed_target:'104',capital_available:'100000',risk_per_trade_percent:'1',lot_size:'25'})){fireEvent.change(screen.getByLabelText(label),{target:{value}})}fireEvent.click(screen.getByText('Risk Validate'));await waitFor(()=>expect(screen.getByText('Risk decision: APPROVED')).toBeTruthy());const execute=screen.getByText('Execute PAPER trade') as HTMLButtonElement;expect(execute.disabled).toBe(true);fireEvent.click(screen.getByLabelText('I authorize this PAPER trade'));await waitFor(()=>expect(execute.disabled).toBe(false));fireEvent.change(screen.getByLabelText('proposed_target'),{target:{value:'105'}});await waitFor(()=>expect(execute.disabled).toBe(true))});
 it('renders rejected paper risk and keeps execution disabled',async()=>{vi.mocked(api).mockImplementation(async(path:string)=>path==='/api/v1/risk/validate'?{result:{risk_decision:{approved:false,rejection_reason:'Risk too high'}}}:{status:'OK',message:'F&O DATA NOT AVAILABLE'});render(<App/>);fireEvent.click(screen.getByText('Paper Trading'));for(const [label,value] of Object.entries({proposed_entry:'100',proposed_stop:'98',proposed_target:'104',capital_available:'100000',risk_per_trade_percent:'1',lot_size:'25'})){fireEvent.change(screen.getByLabelText(label),{target:{value}})}fireEvent.click(screen.getByText('Risk Validate'));await waitFor(()=>expect(screen.getByText(/Risk decision:/)).toBeTruthy());const execute=screen.getByText('Execute PAPER trade') as HTMLButtonElement;const checkbox=screen.getByLabelText('I authorize this PAPER trade') as HTMLInputElement;fireEvent.click(checkbox);expect(execute.disabled).toBe(true);});
 it('renders safe risk API error and blocks paper execution',async()=>{vi.mocked(api).mockImplementation(async(path:string)=>{ if(path==='/api/v1/risk/validate'){ throw new Error('risk fail'); } return {status:'OK',message:'F&O DATA NOT AVAILABLE'}; }); render(<App/>); fireEvent.click(screen.getByText('Paper Trading')); for(const [label,value] of Object.entries({proposed_entry:'100',proposed_stop:'98',proposed_target:'104',capital_available:'100000',risk_per_trade_percent:'1',lot_size:'25'})){ fireEvent.change(screen.getByLabelText(label),{target:{value}});} fireEvent.click(screen.getByText('Risk Validate')); await waitFor(()=>expect(screen.getByText('Request unavailable.')).toBeTruthy()); expect((screen.getByText('Execute PAPER trade') as HTMLButtonElement).disabled).toBe(true); });
 it('allows approved paper execution only after explicit authorization',async()=>{const mock=vi.mocked(api); mock.mockImplementation(async(path:string,options?:any)=>{ if(path==='/api/v1/risk/validate'){ return {result:{risk_decision:{approved:true}}}; } if(path==='/api/v1/paper/execute'){ return {status:'OK',result:{paper_result:{accepted:true,order_id:'P-42'}}}; } return {status:'OK',message:'F&O DATA NOT AVAILABLE'}; }); render(<App/>); fireEvent.click(screen.getByText('Paper Trading')); for(const [label,value] of Object.entries({proposed_entry:'100',proposed_stop:'98',proposed_target:'104',capital_available:'100000',risk_per_trade_percent:'1',lot_size:'25'})){ fireEvent.change(screen.getByLabelText(label),{target:{value}});} fireEvent.click(screen.getByText('Risk Validate')); await waitFor(()=>expect(screen.getByText('Risk decision: APPROVED')).toBeTruthy()); const execute=screen.getByText('Execute PAPER trade') as HTMLButtonElement; expect(execute.disabled).toBe(true); fireEvent.click(screen.getByLabelText('I authorize this PAPER trade')); await waitFor(()=>expect(execute.disabled).toBe(false)); fireEvent.click(execute); await waitFor(()=>expect(mock.mock.calls.filter(([path])=>path==='/api/v1/paper/execute')).toHaveLength(1)); });
 it('renders automation jobs and history and allows a single tick request',async()=>{vi.mocked(api).mockImplementation(async(path:string)=>{ if(path==='/api/v1/automation/jobs'){ return {jobs:[{job_id:'J-1',job_name:'Alpha',enabled:true,schedule_type:'DAILY',execution_mode:'PAPER'}]}; } if(path==='/api/v1/automation/history'){ return {history:[{run_id:'R-1',status:'SUCCESS',retry_count:1,timestamp:'2024-01-01T00:00:00Z'}]}; } if(path==='/api/v1/automation/tick'){ return {status:'OK',message:'Tick accepted'}; } return {status:'OK',message:'F&O DATA NOT AVAILABLE'}; }); render(<App/>); fireEvent.click(screen.getByText('Automation')); fireEvent.click(screen.getByText('Jobs')); await waitFor(()=>expect(screen.getByText('J-1')).toBeTruthy()); fireEvent.click(screen.getByText('Run Tick')); await waitFor(()=>expect(vi.mocked(api).mock.calls.filter(([path])=>path==='/api/v1/automation/tick')).toHaveLength(1)); });
 it('renders the allowlisted Tools view and exact plan controls',async()=>{vi.mocked(api).mockImplementation(async(path:string)=>{ if(path==='/api/v1/tools'){ return {tools:[{tool_id:'system.status',risk_class:'READ_ONLY'}]}; } if(path==='/api/v1/tools/plan'){ return {plan:{plan_id:'PLAN-1'}}; } return {status:'OK',message:'F&O DATA NOT AVAILABLE'}; }); render(<App/>); fireEvent.click(screen.getByText('Tools')); fireEvent.click(screen.getByText('Refresh Tools')); await waitFor(()=>expect(screen.getByText(/system.status/)).toBeTruthy()); fireEvent.click(screen.getByText('Plan Tool')); await waitFor(()=>expect(screen.getByText(/PLAN-1/)).toBeTruthy()); expect(screen.getByText('Approve Exact Plan')).toBeTruthy(); expect(screen.getByText('Execute Plan')).toBeTruthy(); });
});