import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, BarChart3, MessageSquare, Settings, ShieldCheck } from 'lucide-react';
import { api } from './api/client';
import { ResultPanel } from './components/ResultPanel';
import { VoicePanel } from './components/VoicePanel';
import type { VoiceLanguage } from './voice/types';
import './style.css';

type Data = Record<string, unknown>;
const navigation = [['Dashboard', Activity], ['Chat', MessageSquare], ['Analysis', BarChart3], ['Portfolio', ShieldCheck], ['Memory', Settings], ['Tools', Settings], ['Workflows', Settings], ['Projects', Settings], ['Connectors', Settings], ['Governance', Settings], ['Paper Trading', ShieldCheck], ['Backtests', BarChart3], ['Automation', Settings], ['System', Settings]] as const;

export function App() {
  const [view, setView] = useState('Dashboard');
  const [data, setData] = useState<Data>({});
  const [busy, setBusy] = useState(false);
  const [text, setText] = useState('Analyse JARVIS');
  const [symbol, setSymbol] = useState('JARVIS');
  const [authorized, setAuthorized] = useState(false);
  const [riskApproved, setRiskApproved] = useState(false);
  const [proposal, setProposal] = useState<Data>({instrument: 'JARVIS', direction: 'LONG', proposed_entry: '', proposed_stop: '', proposed_target: '', capital_available: '', risk_per_trade_percent: '', lot_size: ''});
  const [memoryKey, setMemoryKey] = useState('preferred_language');
  const [memoryValue, setMemoryValue] = useState('');
  const [toolId, setToolId] = useState('system.status');
  const [toolPlanId, setToolPlanId] = useState('');
  const [workflowId, setWorkflowId] = useState('');
  const load = async (path: string, body?: Data, method = 'POST'): Promise<Data | undefined> => {
    setBusy(true);
    try {
      const response = await api(path, body ? {method, body: JSON.stringify(body)} : (method === 'DELETE' ? {method} : {}));
      setData(response);
      const result = (response as Data).result as Data | undefined;
      setRiskApproved(Boolean((result?.risk_decision as Data | undefined)?.approved));
      return response as Data;
    } catch {
      setData({status: 'ERROR', message: 'Request unavailable.'});
      setRiskApproved(false);
      return undefined;
    } finally { setBusy(false); }
  };
  const submitChat = (message: string, language: VoiceLanguage) => load('/api/v1/chat', {text: message, language: language || 'auto', timestamp: new Date().toISOString()});
  useEffect(() => { load('/api/v1/diagnostics'); }, []);
  const complete = Object.values(proposal).every(Boolean);
  const update = (key: string, value: string) => { setProposal({...proposal, [key]: value}); setRiskApproved(false); };
  const rows = (data.jobs || data.history || []) as Data[];
  return <main><aside><h1>J.A.R.V.I.S</h1>{navigation.map(([name, Icon]) => <button key={name} className={view === name ? 'active' : ''} onClick={() => setView(name)}><Icon size={16}/>{name}</button>)}</aside><section><header><div><small>{view.toUpperCase()}</small><h2>{view}</h2></div><b className="mode">LIVE EXECUTION: UNSUPPORTED</b></header>
    {view === 'Chat' && <><div className="panel"><div className="chat">{String(data.message || 'Ask J.A.R.V.I.S for a deterministic analysis.')}</div>{Boolean(data.intent) && <p>Intent: {String(data.intent)}</p>}{Boolean(data.follow_up_required) && <p>FOLLOW_UP_REQUIRED</p>}{Boolean(data.missing_fields) && <p>Missing: {String(data.missing_fields)}</p>}{Boolean(data.warnings) && <p>Warnings: {String(data.warnings)}</p>}<label>Message<input value={text} onChange={event => setText(event.target.value)}/></label><button className="command" onClick={() => submitChat(text, 'en-IN')}>Send</button></div><VoicePanel submitChat={submitChat}/></>}
    {view === 'Analysis' && <div className="panel"><label>Symbol<input value={symbol} onChange={event => setSymbol(event.target.value.toUpperCase())}/></label><div className="actions"><button onClick={() => load('/api/v1/analysis/market-context', {instrument: symbol, exchange: 'NSE', token: '000001', timestamp: new Date().toISOString()})}>Market Context</button><button onClick={() => load('/api/v1/analysis/underlying', {instrument: symbol, exchange: 'NSE', token: '000001', timestamp: new Date().toISOString()})}>Underlying</button><button className="command" onClick={() => load('/api/v1/analysis/full', {instrument: symbol, exchange: 'NSE', token: '000001', timestamp: new Date().toISOString()})}>Full Analysis</button></div></div>}
    {view === 'Portfolio' && <button className="command" onClick={() => load('/api/v1/portfolio')}>Load Portfolio</button>}
    {view === 'Memory' && <div className="panel"><p className="empty">Memory stores selected personal context locally in JARVIS. Durable memory is never financial authority.</p><div className="actions"><button onClick={() => load('/api/v1/memory')}>Refresh</button></div><label>Key<input value={memoryKey} onChange={event => setMemoryKey(event.target.value)}/></label><label>Value<input value={memoryValue} onChange={event => setMemoryValue(event.target.value)}/></label><button className="command" onClick={() => load('/api/v1/memory', {category:'PREFERENCE',key:memoryKey,value:memoryValue,scope:'DURABLE'})} disabled={!memoryKey || !memoryValue}>Add Memory</button>{((data.memories || []) as Data[]).map(item => <div className="memory-row" key={String(item.memory_id)}><strong>{String(item.key)}</strong><span>{String(item.value)}</span><small>{String(item.source)} · {String(item.updated_at)}</small><button onClick={() => load(`/api/v1/memory/${String(item.memory_id)}`, {value: String(item.value)}, 'PATCH')}>Edit</button><button onClick={() => load(`/api/v1/memory/${String(item.memory_id)}`, undefined, 'DELETE')}>Forget</button></div>)}</div>}
    {view === 'Tools' && <div className="panel"><p className="empty">Allowlisted internal tools only. Protected actions require approval for this exact plan.</p><button onClick={async () => { const response = await load('/api/v1/tools'); setData(response || {}); }}>Refresh Tools</button><label>Tool<select aria-label="Tool selection" value={toolId} onChange={event => setToolId(event.target.value)}>{((data.tools || []) as Data[]).map(tool => <option key={String(tool.tool_id)} value={String(tool.tool_id)}>{String(tool.tool_id)} · {String(tool.risk_class)}</option>)}</select></label><button className="command" onClick={async () => { const response = await load('/api/v1/tools/plan', {tool_id:toolId,arguments:{}}); setToolPlanId(String((response?.plan as Data | undefined)?.plan_id || '')); }}>Plan Tool</button>{toolPlanId && <div className="tool-plan"><p>Plan: {toolPlanId}</p><button onClick={() => load(`/api/v1/tools/${toolPlanId}/approve`)} >Approve Exact Plan</button><button className="command" onClick={() => load(`/api/v1/tools/${toolPlanId}/execute`)}>Execute Plan</button></div>}</div>}
    {view === 'Workflows' && <div className="panel"><p className="empty">Workflows are planned first and never resume automatically after approval or restart.</p><button onClick={async () => { const response = await load('/api/v1/workflows'); setData(response || {}); }}>Refresh Workflows</button>{((data.workflows || []) as Data[]).map(workflow => <div className="memory-row" key={String(workflow.workflow_id)}><strong>{String(workflow.title)}</strong><span>{String(workflow.status)}</span><small>{String(workflow.workflow_id)}</small><button onClick={() => setWorkflowId(String(workflow.workflow_id))}>Show</button><button className="command" onClick={() => load(`/api/v1/workflows/${String(workflow.workflow_id)}/run`)}>Run Workflow</button></div>)}{workflowId && <div className="tool-plan"><p>Workflow: {workflowId}</p><button onClick={() => load(`/api/v1/workflows/${workflowId}/resume`)}>Resume Workflow</button><button onClick={() => load(`/api/v1/workflows/${workflowId}/cancel`)}>Cancel Workflow</button></div>}</div>}
    {view === 'Connectors' && <div className="panel"><p className="empty">Read-only connectors only. Credentials remain server-side; external content is untrusted data.</p><button onClick={async () => { const response = await load('/api/v1/connectors'); setData(response || {}); }}>Refresh Connectors</button>{((data.connectors || []) as Data[]).map(connector => <div className="memory-row" key={String(connector.connector_id)}><strong>{String(connector.display_name)}</strong><span>{String(connector.kind)} · {String(connector.read_only ? 'READ_ONLY' : 'BLOCKED')}</span><small>{String(connector.connector_id)} · configured={String(connector.configured)}</small><button onClick={() => load(`/api/v1/connectors/${String(connector.connector_id)}/capabilities`)}>Capabilities</button></div>)}</div>}
    {view === 'Governance' && <div className="panel"><p className="empty">External write governance is default-deny. Token presence is not permission. Exact repositories and capabilities are required.</p><button onClick={async () => { const response = await load('/api/v1/governance/connectors'); setData(response || {}); }}>Refresh Governance</button>{((data.profiles || []) as Data[]).map(profile => <div className="memory-row" key={String(profile.profile_id)}><strong>{String(profile.connector_id)}</strong><span>{String(profile.environment)} · {String(profile.enabled ? 'ENABLED' : 'DISABLED')}</span><small>Policy version {String(profile.version)} · Resources: {String((profile.allowed_resources as string[] | undefined)?.join(', ') || 'NONE')}</small><span>{String((profile.allowed_capabilities as string[] | undefined)?.join(', ') || 'NONE')}</span></div>)}</div>}
    {view === 'Projects' && <div className="panel"><p className="empty">External read-only project data. Correlations require explicit Jira issue-key evidence; no status is inferred.</p><button onClick={async () => { const response = await load('/api/v1/projects'); setData(response || {}); }}>Refresh Projects</button>{((data.workspaces || []) as Data[]).map(workspace => <div className="memory-row" key={String(workspace.workspace_id)}><strong>{String(workspace.name)}</strong><span>{String(workspace.jira_project_key)} · {String(workspace.github_owner)}/{String(workspace.github_repo)}</span><small>Version {String(workspace.version)}</small><button className="command" onClick={() => load(`/api/v1/projects/${String(workspace.workspace_id)}/snapshot`)}>Refresh Project</button></div>)}{Boolean(data.snapshot) && <div className="tool-plan"><strong>Snapshot</strong><span>Jira: {String((data.snapshot as Data).jira_available)} · GitHub: {String((data.snapshot as Data).github_available)}</span><span>Links: {String(((data.snapshot as Data).links as unknown[] | undefined)?.length || 0)}</span></div>}</div>}
    {view === 'Automation' && <><div className="actions"><button onClick={() => load('/api/v1/automation/jobs')}>Jobs</button><button onClick={() => load('/api/v1/automation/history')}>History</button><button onClick={() => load('/api/v1/automation/tick', {timestamp: new Date().toISOString()})}>Run Tick</button></div>{rows.length > 0 && <table><thead><tr><th>ID</th><th>Status</th><th>Schedule</th><th>Retry</th></tr></thead><tbody>{rows.map((row, index) => <tr key={index}><td>{String(row.job_id || row.run_id || 'NOT_AVAILABLE')}</td><td>{String(row.status || row.enabled || 'NOT_AVAILABLE')}</td><td>{String(row.schedule_type || row.execution_mode || 'NOT_AVAILABLE')}</td><td>{String(row.retry_count || 'NOT_AVAILABLE')}</td></tr>)}</tbody></table>}</>}
    {view === 'System' && <div className="actions"><button onClick={() => load('/health')}>Health</button><button onClick={() => load('/api/v1/readiness')}>Readiness</button><button onClick={() => load('/api/v1/metrics')}>Metrics</button><button onClick={() => load('/api/v1/diagnostics')}>Diagnostics</button></div>}
    {view === 'Backtests' && <p className="empty">HISTORICAL REPLAY: provide local candle JSON through the API.</p>}
    {view === 'Paper Trading' && <div className="panel"><p className="empty">PAPER TRADING only. Risk validation is required before execution.</p>{Object.keys(proposal).map(key => <label key={key}>{key}<input value={String(proposal[key])} onChange={event => update(key, event.target.value)}/></label>)}<button onClick={() => load('/api/v1/risk/validate', proposal)} disabled={!complete}>Risk Validate</button><p>Risk decision: {riskApproved ? 'APPROVED' : 'NOT_AVAILABLE'}</p><label><input type="checkbox" checked={authorized} onChange={event => setAuthorized(event.target.checked)}/>I authorize this PAPER trade</label><button className="command" disabled={!complete || !authorized || !riskApproved} onClick={() => load('/api/v1/paper/execute', {...proposal, explicit_user_authorization: true})}>Execute PAPER trade</button></div>}
    <article aria-live="polite">{busy ? 'LOADING...' : <ResultPanel data={data}/>}</article></section></main>;
}
const root = document.getElementById('root');
if (root) createRoot(root).render(<App/>);
